export const SET_COORDINATES = 'ADD_COORDINATES';
export const SAVE_ADDRESS = 'SAVE_ADDRESS';
export const ALL_STORES = 'ALL_STORES';
export const STORES_TO_PRINT = 'STORES_TO_PRINT';
export const STORES_SELECTED = 'STORES_SELECTED';
export const STORE_TO_DETAIL = 'STORE_TO_DETAIL'; 
export const PRODUCTS_TO_PRINT = 'PRODUCTS_TO_PRINT';
export const RESET_PRODUCTS_TO_PRINT = 'RESET_PRODUCTS_TO_PRINT';