export const SET_COORDINATES = 'ADD_COORDINATES';
export const SAVE_ADDRESS = 'SAVE_ADDRESS';
export const STORES_TO_PRINT = 'STORES_TO_PRINT';
export const STORES_SELECTED = 'STORES_SELECTED';
export const STORE_TO_DETAIL = 'STORE_TO_DETAIL'; 