export const SET_COORDINATES = 'ADD_COORDINATES';
export const SAVE_ADDRESS = 'SAVE_ADDRESS';

export const ALL_STORES = 'ALL_STORES';
export const STORES_TO_PRINT = 'STORES_TO_PRINT';
export const STORES_SELECTED = 'STORES_SELECTED';
export const STORE_TO_DETAIL = 'STORE_TO_DETAIL'; 

export const PRODUCTS_TO_PRINT = 'PRODUCTS_TO_PRINT';
export const RESET_PRODUCTS_TO_PRINT = 'RESET_PRODUCTS_TO_PRINT';
export const UPDATE_PRODUCTS_TO_PRINT = 'UPDATE_PRODUCTS_TO_PRINT';

export const UPDATE_ORDER = 'UPDATE_ORDER';
export const UPDATE_TOTAL_PRICE = 'UPDATE_TOTAL_PRICE';

export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const SAVE_CONTACT = 'SAVE_CONTACT';

export const SET_PAGE = 'SET_PAGE';
export const UPDATE_CATEGORIES_ACTIVATION = 'UPDATE_CATEGORIES_ACTIVATION';
export const UPDATE_ORDER_ACTIVATION = 'UPDATE_ORDER_ACTIVATION';